/**
 * AUTO-GENERATED by scripts/codegen.mjs — do not edit manually.
 * Source: src/types/AgreementTypes.sol, src/BCConfig.sol
 */

import type { Address } from "viem";

export const ChildContractScope = {
  None: 0,
  ExistingOnly: 1,
  All: 2,
  FutureOnly: 3,
} as const;
export type ChildContractScope =
  (typeof ChildContractScope)[keyof typeof ChildContractScope];

export const IdentityRequirements = {
  Anonymous: 0,
  Pseudonymous: 1,
  Named: 2,
} as const;
export type IdentityRequirements =
  (typeof IdentityRequirements)[keyof typeof IdentityRequirements];

export interface Contact {
  readonly name: string;
  readonly contact: string;
}

export interface BcAccount {
  readonly accountAddress: string;
  readonly childContractScope: ChildContractScope;
}

export interface BcChain {
  readonly assetRecoveryAddress: string;
  readonly accounts: readonly BcAccount[];
  readonly caip2ChainId: string;
}

export interface BountyTerms {
  readonly bountyPercentage: bigint;
  readonly bountyCapUsd: bigint;
  readonly retainable: boolean;
  readonly identity: IdentityRequirements;
  readonly diligenceRequirements: string;
  readonly aggregateBountyCapUsd: bigint;
}

export interface AgreementDetails {
  readonly protocolName: string;
  readonly contactDetails: readonly Contact[];
  readonly chains: readonly BcChain[];
  readonly bountyTerms: BountyTerms;
  readonly agreementURI: string;
}

export interface BcNetworkConfig {
  readonly chainId: number;
  readonly caip2: string;
  readonly registry: Address;
  readonly factory: Address;
  readonly attackRegistry: Address;
  readonly deployer: Address;
  readonly createX: Address;
  readonly safeHarborUri: string;
}
