/**
 * ABI fragments for BattleChain protocol contracts.
 *
 * Auto-generated by tools/gen-abi.ts from the canonical battlechain-lib ABI
 * artifacts (../../abis/*.json). Do not edit manually — regenerate with
 * `npm run gen-abi`.
 */

/* eslint-disable */

// Source: abis/agreementFactory.json
export const AGREEMENT_FACTORY_ABI = [
  {
    "type": "function",
    "name": "create",
    "inputs": [
      {
        "name": "details",
        "type": "tuple",
        "internalType": "struct AgreementDetails",
        "components": [
          {
            "name": "protocolName",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "contactDetails",
            "type": "tuple[]",
            "internalType": "struct Contact[]",
            "components": [
              {
                "name": "name",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "contact",
                "type": "string",
                "internalType": "string"
              }
            ]
          },
          {
            "name": "chains",
            "type": "tuple[]",
            "internalType": "struct Chain[]",
            "components": [
              {
                "name": "assetRecoveryAddress",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "accounts",
                "type": "tuple[]",
                "internalType": "struct Account[]",
                "components": [
                  {
                    "name": "accountAddress",
                    "type": "string",
                    "internalType": "string"
                  },
                  {
                    "name": "childContractScope",
                    "type": "uint8",
                    "internalType": "enum ChildContractScope"
                  }
                ]
              },
              {
                "name": "caip2ChainId",
                "type": "string",
                "internalType": "string"
              }
            ]
          },
          {
            "name": "bountyTerms",
            "type": "tuple",
            "internalType": "struct BountyTerms",
            "components": [
              {
                "name": "bountyPercentage",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bountyCapUsd",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "retainable",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "identity",
                "type": "uint8",
                "internalType": "enum IdentityRequirements"
              },
              {
                "name": "diligenceRequirements",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "aggregateBountyCapUsd",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          },
          {
            "name": "agreementURI",
            "type": "string",
            "internalType": "string"
          }
        ]
      },
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "salt",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "agreementAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getBattleChainCaip2ChainId",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getRegistry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isAgreementContract",
    "inputs": [
      {
        "name": "agreementAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  }
] as const;

// Source: abis/agreement.json
export const AGREEMENT_ABI = [
  {
    "type": "function",
    "name": "addAccounts",
    "inputs": [
      {
        "name": "caip2ChainId",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "newAccounts",
        "type": "tuple[]",
        "internalType": "struct Account[]",
        "components": [
          {
            "name": "accountAddress",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "childContractScope",
            "type": "uint8",
            "internalType": "enum ChildContractScope"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "addOrSetChains",
    "inputs": [
      {
        "name": "chains",
        "type": "tuple[]",
        "internalType": "struct Chain[]",
        "components": [
          {
            "name": "assetRecoveryAddress",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "accounts",
            "type": "tuple[]",
            "internalType": "struct Account[]",
            "components": [
              {
                "name": "accountAddress",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "childContractScope",
                "type": "uint8",
                "internalType": "enum ChildContractScope"
              }
            ]
          },
          {
            "name": "caip2ChainId",
            "type": "string",
            "internalType": "string"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "extendCommitmentWindow",
    "inputs": [
      {
        "name": "newCantChangeUntil",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getAgreementURI",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getBattleChainCaip2ChainId",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getBattleChainScopeAddresses",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getBattleChainScopeCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getBountyTerms",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct BountyTerms",
        "components": [
          {
            "name": "bountyPercentage",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "bountyCapUsd",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "retainable",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "identity",
            "type": "uint8",
            "internalType": "enum IdentityRequirements"
          },
          {
            "name": "diligenceRequirements",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "aggregateBountyCapUsd",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getCantChangeUntil",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getChainIds",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string[]",
        "internalType": "string[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getDetails",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct AgreementDetails",
        "components": [
          {
            "name": "protocolName",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "contactDetails",
            "type": "tuple[]",
            "internalType": "struct Contact[]",
            "components": [
              {
                "name": "name",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "contact",
                "type": "string",
                "internalType": "string"
              }
            ]
          },
          {
            "name": "chains",
            "type": "tuple[]",
            "internalType": "struct Chain[]",
            "components": [
              {
                "name": "assetRecoveryAddress",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "accounts",
                "type": "tuple[]",
                "internalType": "struct Account[]",
                "components": [
                  {
                    "name": "accountAddress",
                    "type": "string",
                    "internalType": "string"
                  },
                  {
                    "name": "childContractScope",
                    "type": "uint8",
                    "internalType": "enum ChildContractScope"
                  }
                ]
              },
              {
                "name": "caip2ChainId",
                "type": "string",
                "internalType": "string"
              }
            ]
          },
          {
            "name": "bountyTerms",
            "type": "tuple",
            "internalType": "struct BountyTerms",
            "components": [
              {
                "name": "bountyPercentage",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bountyCapUsd",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "retainable",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "identity",
                "type": "uint8",
                "internalType": "enum IdentityRequirements"
              },
              {
                "name": "diligenceRequirements",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "aggregateBountyCapUsd",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          },
          {
            "name": "agreementURI",
            "type": "string",
            "internalType": "string"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getProtocolName",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getRegistry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isContractInScope",
    "inputs": [
      {
        "name": "contractAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "removeAccounts",
    "inputs": [
      {
        "name": "caip2ChainId",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "accountAddresses",
        "type": "string[]",
        "internalType": "string[]"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "removeChains",
    "inputs": [
      {
        "name": "caip2ChainIds",
        "type": "string[]",
        "internalType": "string[]"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setAgreementURI",
    "inputs": [
      {
        "name": "agreementURI",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setBountyTerms",
    "inputs": [
      {
        "name": "bountyTerms",
        "type": "tuple",
        "internalType": "struct BountyTerms",
        "components": [
          {
            "name": "bountyPercentage",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "bountyCapUsd",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "retainable",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "identity",
            "type": "uint8",
            "internalType": "enum IdentityRequirements"
          },
          {
            "name": "diligenceRequirements",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "aggregateBountyCapUsd",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setContactDetails",
    "inputs": [
      {
        "name": "contactDetails",
        "type": "tuple[]",
        "internalType": "struct Contact[]",
        "components": [
          {
            "name": "name",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "contact",
            "type": "string",
            "internalType": "string"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setProtocolName",
    "inputs": [
      {
        "name": "protocolName",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  }
] as const;

// Source: abis/attackRegistry.json
export const ATTACK_REGISTRY_ABI = [
  {
    "type": "function",
    "name": "approveAttack",
    "inputs": [
      {
        "name": "agreementAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "authorizeAgreementOwner",
    "inputs": [
      {
        "name": "contractAddress",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "cancelPromotion",
    "inputs": [
      {
        "name": "agreementAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "changeRegistryModerator",
    "inputs": [
      {
        "name": "newModerator",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getAgreementForContract",
    "inputs": [
      {
        "name": "contractAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getAgreementInfo",
    "inputs": [
      {
        "name": "agreementAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IAttackRegistry.AgreementInfo",
        "components": [
          {
            "name": "attackModerator",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "deadlineTimestamp",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "promotionRequestedTimestamp",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "attackRequested",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "attackApproved",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "promoted",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "corrupted",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "isRegistered",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getAgreementState",
    "inputs": [
      {
        "name": "agreementAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "enum IAttackRegistry.ContractState"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getAttackModerator",
    "inputs": [
      {
        "name": "agreementAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getAuthorizedOwner",
    "inputs": [
      {
        "name": "contractAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getRegistryModerator",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getSafeHarborRegistry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "goToProduction",
    "inputs": [
      {
        "name": "agreementAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "instantCorrupt",
    "inputs": [
      {
        "name": "agreementAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "instantPromote",
    "inputs": [
      {
        "name": "agreementAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "isTopLevelContractUnderAttack",
    "inputs": [
      {
        "name": "contractAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "markCorrupted",
    "inputs": [
      {
        "name": "agreementAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "promote",
    "inputs": [
      {
        "name": "agreementAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "registerContractForExistingAgreement",
    "inputs": [
      {
        "name": "contractAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "registerDeployment",
    "inputs": [
      {
        "name": "contractAddress",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "deployer",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "rejectAttackRequest",
    "inputs": [
      {
        "name": "agreementAddress",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "slashBond",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "requestUnderAttack",
    "inputs": [
      {
        "name": "agreementAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "requestUnderAttackByNonAuthorized",
    "inputs": [
      {
        "name": "agreementAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "requestUnderAttackForUnverifiedContracts",
    "inputs": [
      {
        "name": "agreementAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setSafeHarborRegistry",
    "inputs": [
      {
        "name": "newRegistry",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "syncNewContracts",
    "inputs": [
      {
        "name": "agreementAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferAttackModerator",
    "inputs": [
      {
        "name": "agreementAddress",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "newModerator",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "unregisterContractForExistingAgreement",
    "inputs": [
      {
        "name": "contractAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  }
] as const;

// Source: abis/registry.json
export const REGISTRY_ABI = [
  {
    "type": "function",
    "name": "adoptSafeHarbor",
    "inputs": [
      {
        "name": "agreementAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getAgreement",
    "inputs": [
      {
        "name": "adopter",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getAgreementFactory",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getAttackRegistry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isAgreementValid",
    "inputs": [
      {
        "name": "agreementAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isChainValid",
    "inputs": [
      {
        "name": "caip2ChainId",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setAgreementFactory",
    "inputs": [
      {
        "name": "factory",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  }
] as const;

// Source: abis/deployer.json
export const DEPLOYER_ABI = [
  {
    "type": "function",
    "name": "computeCreate2Address",
    "inputs": [
      {
        "name": "salt",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "initCodeHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "computedAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "computeCreate2Address",
    "inputs": [
      {
        "name": "salt",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "initCodeHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "deployer",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "computedAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "computeCreate3Address",
    "inputs": [
      {
        "name": "salt",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "deployer",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "computedAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "computeCreate3Address",
    "inputs": [
      {
        "name": "salt",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "computedAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "computeCreateAddress",
    "inputs": [
      {
        "name": "nonce",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "computedAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "computeCreateAddress",
    "inputs": [
      {
        "name": "deployer",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "nonce",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "computedAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "deployCreate",
    "inputs": [
      {
        "name": "initCode",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "newContract",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "deployCreate2",
    "inputs": [
      {
        "name": "salt",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "initCode",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "newContract",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "deployCreate2",
    "inputs": [
      {
        "name": "initCode",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "newContract",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "deployCreate2AndInit",
    "inputs": [
      {
        "name": "salt",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "initCode",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "values",
        "type": "tuple",
        "internalType": "struct IBattleChainDeployer.Values",
        "components": [
          {
            "name": "constructorAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "initCallAmount",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "refundAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "newContract",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "deployCreate2AndInit",
    "inputs": [
      {
        "name": "initCode",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "values",
        "type": "tuple",
        "internalType": "struct IBattleChainDeployer.Values",
        "components": [
          {
            "name": "constructorAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "initCallAmount",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "newContract",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "deployCreate2AndInit",
    "inputs": [
      {
        "name": "initCode",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "values",
        "type": "tuple",
        "internalType": "struct IBattleChainDeployer.Values",
        "components": [
          {
            "name": "constructorAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "initCallAmount",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "refundAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "newContract",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "deployCreate2AndInit",
    "inputs": [
      {
        "name": "salt",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "initCode",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "values",
        "type": "tuple",
        "internalType": "struct IBattleChainDeployer.Values",
        "components": [
          {
            "name": "constructorAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "initCallAmount",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "newContract",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "deployCreate2Clone",
    "inputs": [
      {
        "name": "salt",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "implementation",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "proxy",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "deployCreate2Clone",
    "inputs": [
      {
        "name": "implementation",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "proxy",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "deployCreate3",
    "inputs": [
      {
        "name": "initCode",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "newContract",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "deployCreate3",
    "inputs": [
      {
        "name": "salt",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "initCode",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "newContract",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "deployCreate3AndInit",
    "inputs": [
      {
        "name": "salt",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "initCode",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "values",
        "type": "tuple",
        "internalType": "struct IBattleChainDeployer.Values",
        "components": [
          {
            "name": "constructorAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "initCallAmount",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "newContract",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "deployCreate3AndInit",
    "inputs": [
      {
        "name": "initCode",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "values",
        "type": "tuple",
        "internalType": "struct IBattleChainDeployer.Values",
        "components": [
          {
            "name": "constructorAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "initCallAmount",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "newContract",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "deployCreate3AndInit",
    "inputs": [
      {
        "name": "salt",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "initCode",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "values",
        "type": "tuple",
        "internalType": "struct IBattleChainDeployer.Values",
        "components": [
          {
            "name": "constructorAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "initCallAmount",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "refundAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "newContract",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "deployCreate3AndInit",
    "inputs": [
      {
        "name": "initCode",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "values",
        "type": "tuple",
        "internalType": "struct IBattleChainDeployer.Values",
        "components": [
          {
            "name": "constructorAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "initCallAmount",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "refundAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "newContract",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "deployCreateAndInit",
    "inputs": [
      {
        "name": "initCode",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "values",
        "type": "tuple",
        "internalType": "struct IBattleChainDeployer.Values",
        "components": [
          {
            "name": "constructorAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "initCallAmount",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "newContract",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "deployCreateAndInit",
    "inputs": [
      {
        "name": "initCode",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "values",
        "type": "tuple",
        "internalType": "struct IBattleChainDeployer.Values",
        "components": [
          {
            "name": "constructorAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "initCallAmount",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "refundAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "newContract",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "deployCreateClone",
    "inputs": [
      {
        "name": "implementation",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "proxy",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  }
] as const;

// Source: abis/registryModerator.json
export const MOCK_REGISTRY_MODERATOR_ABI = [
  {
    "type": "function",
    "name": "approveAttack",
    "inputs": [
      {
        "name": "agreementAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  }
] as const;
