/**
 * Contract data for BattleChain networks.
 *
 * Auto-generated by tools/gen-config.ts from the canonical battlechain-lib
 * deployments artifact (../../deployments.json). Do not edit manually —
 * regenerate with `npm run gen-config`. RPC URLs are a manual overlay sourced
 * from battlechain-lib-py/battlechain/config.py.
 */

/* oxlint-disable */

// -----------------------------------------------------------------------------
// Chain IDs (BCConfig.sol)
// -----------------------------------------------------------------------------

export const MAINNET_CHAIN_ID = 626;
export const TESTNET_CHAIN_ID = 627;

// -----------------------------------------------------------------------------
// CAIP-2 chain ID strings (BCConfig.sol)
// -----------------------------------------------------------------------------

export const MAINNET_CAIP2 = "eip155:626";
export const TESTNET_CAIP2 = "eip155:627";

// -----------------------------------------------------------------------------
// Safe Harbor agreement URIs (BCConfig.sol)
// -----------------------------------------------------------------------------

export const SAFE_HARBOR_V3_URI = "ipfs://bafkreiernns2f4nv2uzvwtzjc2jboyivsu2mixz33y3xo7cvtllsuao6jy";
export const BATTLECHAIN_SAFE_HARBOR_URI = "ipfs://bafkreibrplcrle2zxiezhm2metajrrdqyvwglhakddrdt27elmrezp5bge";

// -----------------------------------------------------------------------------
// RPC URLs (manual overlay — off-chain infra from battlechain-lib-py)
// -----------------------------------------------------------------------------

export const MAINNET_RPC_URL = "https://mainnet.battlechain.com";
export const TESTNET_RPC_URL = "https://testnet.battlechain.com";

// -----------------------------------------------------------------------------
// Block explorer hosts (BCQuery.sol)
// -----------------------------------------------------------------------------

export const MAINNET_EXPLORER_HOST = "https://block-explorer-api.mainnet.battlechain.com";
export const TESTNET_EXPLORER_HOST = "https://block-explorer-api.testnet.battlechain.com";

// -----------------------------------------------------------------------------
// Contract addresses (BCConfig.sol)
// -----------------------------------------------------------------------------

export const WELL_KNOWN_CREATEX = "0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed";
export const MAINNET_REGISTRY = "0xd229f4EE1bAE432010b72a9d1bD682570F4C6eBe";
export const MAINNET_AGREEMENT_FACTORY = "0xCdB7F5C0F708baBaabE82afE1DbA8362023AcFdd";
export const MAINNET_ATTACK_REGISTRY = "0x24876e481eC7198CAC95af739Df2a852CE65A415";
export const MAINNET_DEPLOYER = "0xD12765D21dDba418B8Fc0583c4716763e03Aa078";
export const MAINNET_CREATEX = "0xa397f06F07251A3AEd53f6d3019A2a6cbd83E53e";
export const MAINNET_REGISTRY_IMPL = "0x96d9cCEf1C2eBD19Cc4D3293Bd726c335F9523d7";
export const MAINNET_AGREEMENT_FACTORY_IMPL = "0xF52b4B00E6c33ED327886fc64c205a9F2DEc3623";
export const MAINNET_ATTACK_REGISTRY_IMPL = "0x2d226C9f76748C3759F640Ee527Ad0D1A312fbB2";
export const MAINNET_REGISTRY_MODERATOR = "0x445d5685c4Ae71550Da0716b82B434AEA140E0c7";
export const TESTNET_REGISTRY = "0x07E09f67B272aec60eebBfB3D592eC649BDCFEFc";
export const TESTNET_AGREEMENT_FACTORY = "0xf52CEA27b9E20D03Ec48CDe4fafF8F27565646f2";
export const TESTNET_ATTACK_REGISTRY = "0x22134e878c409a0Eab7259d873b38e26Ca966d3C";
export const TESTNET_DEPLOYER = "0x0f75289c6b883b885A1fDF9BCCABE1bbFB094077";
export const TESTNET_CREATEX = "0xf1Ebfaa992854ECcB01Ac1F60e5b5279095cca7F";
export const TESTNET_REGISTRY_IMPL = "0x7d6fC65eA6436f1621973BcfeaAD8951853D8E35";
export const TESTNET_AGREEMENT_FACTORY_IMPL = "0x8E940c4FE62ea1696751faA99F45F30459c6c978";
export const TESTNET_ATTACK_REGISTRY_IMPL = "0x4496b7e04b4Dd94153AA0d614708d5f06fc65a13";
export const TESTNET_MOCK_REGISTRY_MODERATOR = "0x3DdA228A38b4d7438bBF5D5137c8D1090DcaF6bF";

// -----------------------------------------------------------------------------
// CreateX-supported chain IDs (CreateXChains.sol)
// -----------------------------------------------------------------------------

/** Production chains with CreateX at the well-known address. */
export const PRODUCTION_CHAIN_IDS: ReadonlySet<number> = new Set([
  1, 10, 25, 40, 42, 50, 56, 100, 122, 130, 137, 143, 146, 169, 196, 204, 232, 239, 250, 252,
  288, 314, 324, 360, 480, 648, 747, 841, 995, 999, 1088, 1101, 1116, 1135, 1155, 1284, 1285,
  1329, 1514, 1625, 1750, 1868, 1890, 1923, 2020, 2222, 2741, 2818, 2911, 3637, 4114, 4162,
  4326, 4352, 4689, 5000, 5330, 7000, 7700, 7897, 7979, 8217, 8453, 9001, 9745, 13371, 17771,
  23294, 33139, 34443, 42161, 42170, 42220, 42793, 43111, 43114, 48900, 50104, 57073, 59144,
  60808, 80094, 81457, 88888, 98866, 167000, 200901, 534352, 747474, 1440000, 5734951, 7777777,
  21000000, 1313161554, 1666600000,
]);

/** Test/dev chains with CreateX at the well-known address. */
export const TEST_CHAIN_IDS: ReadonlySet<number> = new Set([
  31, 41, 51, 97, 111, 195, 300, 338, 842, 919, 997, 998, 1115, 1287, 1301, 1315, 1328, 1442,
  1740, 1891, 1924, 1946, 2021, 2391, 2523, 2910, 3636, 3939, 4002, 4201, 4202, 4690, 4801,
  5003, 5115, 5611, 6343, 7001, 7701, 9000, 9746, 9897, 10143, 10200, 11011, 11124, 13473,
  13579, 29112, 31337, 33111, 37111, 37373, 42431, 43113, 43522, 53302, 57054, 59141, 59902,
  80002, 80069, 84532, 88882, 127823, 167013, 200810, 314159, 421614, 534351, 560048, 713715,
  737373, 743111, 763373, 1449000, 2019775, 3441006, 5042002, 11142220, 11155111, 11155420,
  21000001, 79479957, 168587773, 531050104, 999999999, 1313161555, 1666700000,
]);
