"""Generated contract data for BattleChain.

AUTO-GENERATED by tools/gen_config.py from deployments.json — do not edit manually.
Regenerate with:
    python tools/gen_config.py [/path/to/deployments.json]

Holds the literal addresses, chain IDs, CAIP-2 strings, URIs, explorer hosts and
CreateX-supported chain lists. Resolution logic lives in config.py and
createx_chains.py, which import from here. RPC URLs are not part of this
artifact and are maintained manually in config.py.
"""

# -----------------------------------------------------------------------------
# Chain IDs
# -----------------------------------------------------------------------------

MAINNET_CHAIN_ID = 626
TESTNET_CHAIN_ID = 627

# -----------------------------------------------------------------------------
# CAIP-2 chain ID strings
# -----------------------------------------------------------------------------

MAINNET_CAIP2 = "eip155:626"
TESTNET_CAIP2 = "eip155:627"

# -----------------------------------------------------------------------------
# CreateX — well-known address, same on all supported chains.
# -----------------------------------------------------------------------------

WELL_KNOWN_CREATEX = "0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed"

# -----------------------------------------------------------------------------
# Safe Harbor agreement URIs
# -----------------------------------------------------------------------------

SAFE_HARBOR_V3_URI = "ipfs://bafkreiernns2f4nv2uzvwtzjc2jboyivsu2mixz33y3xo7cvtllsuao6jy"
BATTLECHAIN_SAFE_HARBOR_URI = "ipfs://bafkreibrplcrle2zxiezhm2metajrrdqyvwglhakddrdt27elmrezp5bge"

# -----------------------------------------------------------------------------
# Block explorer hosts (bare host, no /api suffix)
# -----------------------------------------------------------------------------

MAINNET_EXPLORER_HOST = "https://block-explorer-api.mainnet.battlechain.com"
TESTNET_EXPLORER_HOST = "https://block-explorer-api.testnet.battlechain.com"

# -----------------------------------------------------------------------------
# Mainnet (626) addresses — canonical
# -----------------------------------------------------------------------------

MAINNET_REGISTRY = "0xd229f4EE1bAE432010b72a9d1bD682570F4C6eBe"
MAINNET_AGREEMENT_FACTORY = "0xCdB7F5C0F708baBaabE82afE1DbA8362023AcFdd"
MAINNET_ATTACK_REGISTRY = "0x24876e481eC7198CAC95af739Df2a852CE65A415"
MAINNET_DEPLOYER = "0xD12765D21dDba418B8Fc0583c4716763e03Aa078"
MAINNET_CREATEX = "0xa397f06F07251A3AEd53f6d3019A2a6cbd83E53e"
MAINNET_REGISTRY_IMPL = "0xBFF0ec94740c287932B50E64c2e8b380129B99a1"
MAINNET_AGREEMENT_FACTORY_IMPL = "0x8d4fEDF4462E3876Ae7C70CC0C5cebA482003Ad5"
MAINNET_ATTACK_REGISTRY_IMPL = "0x03A3228A4ce38362289E715bbc26Cac8b98e421B"
MAINNET_REGISTRY_MODERATOR = "0x445d5685c4Ae71550Da0716b82B434AEA140E0c7"

# -----------------------------------------------------------------------------
# Testnet (627) addresses — canonical
# -----------------------------------------------------------------------------

TESTNET_REGISTRY = "0x07E09f67B272aec60eebBfB3D592eC649BDCFEFc"
TESTNET_AGREEMENT_FACTORY = "0xf52CEA27b9E20D03Ec48CDe4fafF8F27565646f2"
TESTNET_ATTACK_REGISTRY = "0x22134e878c409a0Eab7259d873b38e26Ca966d3C"
TESTNET_DEPLOYER = "0x0f75289c6b883b885A1fDF9BCCABE1bbFB094077"
TESTNET_CREATEX = "0xf1Ebfaa992854ECcB01Ac1F60e5b5279095cca7F"
TESTNET_REGISTRY_IMPL = "0x7d6fC65eA6436f1621973BcfeaAD8951853D8E35"
TESTNET_AGREEMENT_FACTORY_IMPL = "0x8E940c4FE62ea1696751faA99F45F30459c6c978"
TESTNET_ATTACK_REGISTRY_IMPL = "0x4496b7e04b4Dd94153AA0d614708d5f06fc65a13"
TESTNET_MOCK_REGISTRY_MODERATOR = "0x3DdA228A38b4d7438bBF5D5137c8D1090DcaF6bF"

# -----------------------------------------------------------------------------
# CreateX-supported chains
# Source: https://github.com/pcaversaccio/createx#createx-deployments
# -----------------------------------------------------------------------------

PRODUCTION_CHAIN_IDS: frozenset[int] = frozenset(
    {
        1,
        10,
        25,
        40,
        42,
        50,
        56,
        100,
        122,
        130,
        137,
        143,
        146,
        169,
        196,
        204,
        232,
        239,
        250,
        252,
        288,
        314,
        324,
        360,
        480,
        648,
        747,
        841,
        995,
        999,
        1088,
        1101,
        1116,
        1135,
        1155,
        1284,
        1285,
        1329,
        1514,
        1625,
        1750,
        1868,
        1890,
        1923,
        2020,
        2222,
        2741,
        2818,
        2911,
        3637,
        4114,
        4162,
        4326,
        4352,
        4689,
        5000,
        5330,
        7000,
        7700,
        7897,
        7979,
        8217,
        8453,
        9001,
        9745,
        13371,
        17771,
        23294,
        33139,
        34443,
        42161,
        42170,
        42220,
        42793,
        43111,
        43114,
        48900,
        50104,
        57073,
        59144,
        60808,
        80094,
        81457,
        88888,
        98866,
        167000,
        200901,
        534352,
        747474,
        1440000,
        5734951,
        7777777,
        21000000,
        1313161554,
        1666600000,
    }
)

TEST_CHAIN_IDS: frozenset[int] = frozenset(
    {
        31,
        41,
        51,
        97,
        111,
        195,
        300,
        338,
        842,
        919,
        997,
        998,
        1115,
        1287,
        1301,
        1315,
        1328,
        1442,
        1740,
        1891,
        1924,
        1946,
        2021,
        2391,
        2523,
        2910,
        3636,
        3939,
        4002,
        4201,
        4202,
        4690,
        4801,
        5003,
        5115,
        5611,
        6343,
        7001,
        7701,
        9000,
        9746,
        9897,
        10143,
        10200,
        11011,
        11124,
        13473,
        13579,
        29112,
        31337,
        33111,
        37111,
        37373,
        42431,
        43113,
        43522,
        53302,
        57054,
        59141,
        59902,
        80002,
        80069,
        84532,
        88882,
        127823,
        167013,
        200810,
        314159,
        421614,
        534351,
        560048,
        713715,
        737373,
        743111,
        763373,
        1449000,
        2019775,
        3441006,
        5042002,
        11142220,
        11155111,
        11155420,
        21000001,
        79479957,
        168587773,
        531050104,
        999999999,
        1313161555,
        1666700000,
    }
)
