"""Regenerate battlechain/_contract_data.py from the root deployments.json.

The canonical source of every address, chain ID, CAIP-2 string, URI, explorer
host and CreateX-supported chain list is the language-neutral artifact emitted
by `scripts/codegen.mjs` at the repository root:
    <battlechain-lib>/deployments.json

This script reads that file and emits `battlechain/_contract_data.py`, the
generated DATA module that `config.py` and `createx_chains.py` import from.
All hand-written resolution logic stays in those modules; only the literal
values live here.

RPC URLs are NOT present in deployments.json and remain a documented manual
overlay in config.py (MAINNET_RPC_URL / TESTNET_RPC_URL).

Usage:
    python tools/gen_config.py                       # defaults to ../../deployments.json
    python tools/gen_config.py /path/to/deployments.json
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

PACKAGE_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_DEPLOYMENTS_PATH = PACKAGE_ROOT.parent.parent / "deployments.json"
TARGET = PACKAGE_ROOT / "battlechain" / "_contract_data.py"


def _format_chain_id_set(name: str, ids: list[int]) -> str:
    """Render a frozenset literal of sorted chain IDs, one per line (ruff-format style)."""
    lines = [f"{name}: frozenset[int] = frozenset(", "    {"]
    for chain_id in sorted(ids):
        lines.append(f"        {chain_id},")
    lines.append("    }")
    lines.append(")")
    return "\n".join(lines)


def render_module(data: dict) -> str:
    networks = data["networks"]
    mainnet = networks[str(data["networks"]["626"]["chainId"])]
    testnet = networks[str(data["networks"]["627"]["chainId"])]
    explorer = networks["_explorer"]

    production = _format_chain_id_set("PRODUCTION_CHAIN_IDS", data["createx"]["production"])
    test = _format_chain_id_set("TEST_CHAIN_IDS", data["createx"]["test"])

    return f'''"""Generated contract data for BattleChain.

AUTO-GENERATED by tools/gen_config.py from deployments.json — do not edit manually.
Regenerate with:
    python tools/gen_config.py [/path/to/deployments.json]

Holds the literal addresses, chain IDs, CAIP-2 strings, URIs, explorer hosts and
CreateX-supported chain lists. Resolution logic lives in config.py and
createx_chains.py, which import from here. RPC URLs are not part of this
artifact and are maintained manually in config.py.
"""

# -----------------------------------------------------------------------------
# Chain IDs
# -----------------------------------------------------------------------------

MAINNET_CHAIN_ID = {mainnet["chainId"]}
TESTNET_CHAIN_ID = {testnet["chainId"]}

# -----------------------------------------------------------------------------
# CAIP-2 chain ID strings
# -----------------------------------------------------------------------------

MAINNET_CAIP2 = "{mainnet["caip2"]}"
TESTNET_CAIP2 = "{testnet["caip2"]}"

# -----------------------------------------------------------------------------
# CreateX — well-known address, same on all supported chains.
# -----------------------------------------------------------------------------

WELL_KNOWN_CREATEX = "{data["wellKnownCreateX"]}"

# -----------------------------------------------------------------------------
# Safe Harbor agreement URIs
# -----------------------------------------------------------------------------

SAFE_HARBOR_V3_URI = "{data["safeHarborV3Uri"]}"
BATTLECHAIN_SAFE_HARBOR_URI = "{data["battlechainSafeHarborUri"]}"

# -----------------------------------------------------------------------------
# Block explorer hosts (bare host, no /api suffix)
# -----------------------------------------------------------------------------

MAINNET_EXPLORER_HOST = "{explorer[str(mainnet["chainId"])]}"
TESTNET_EXPLORER_HOST = "{explorer[str(testnet["chainId"])]}"

# -----------------------------------------------------------------------------
# Mainnet ({mainnet["chainId"]}) addresses — canonical
# -----------------------------------------------------------------------------

MAINNET_REGISTRY = "{mainnet["registry"]}"
MAINNET_AGREEMENT_FACTORY = "{mainnet["agreementFactory"]}"
MAINNET_ATTACK_REGISTRY = "{mainnet["attackRegistry"]}"
MAINNET_DEPLOYER = "{mainnet["deployer"]}"
MAINNET_CREATEX = "{mainnet["createX"]}"
MAINNET_REGISTRY_IMPL = "{mainnet["registryImpl"]}"
MAINNET_AGREEMENT_FACTORY_IMPL = "{mainnet["agreementFactoryImpl"]}"
MAINNET_ATTACK_REGISTRY_IMPL = "{mainnet["attackRegistryImpl"]}"
MAINNET_REGISTRY_MODERATOR = "{mainnet["registryModerator"]}"

# -----------------------------------------------------------------------------
# Testnet ({testnet["chainId"]}) addresses — canonical
# -----------------------------------------------------------------------------

TESTNET_REGISTRY = "{testnet["registry"]}"
TESTNET_AGREEMENT_FACTORY = "{testnet["agreementFactory"]}"
TESTNET_ATTACK_REGISTRY = "{testnet["attackRegistry"]}"
TESTNET_DEPLOYER = "{testnet["deployer"]}"
TESTNET_CREATEX = "{testnet["createX"]}"
TESTNET_REGISTRY_IMPL = "{testnet["registryImpl"]}"
TESTNET_AGREEMENT_FACTORY_IMPL = "{testnet["agreementFactoryImpl"]}"
TESTNET_ATTACK_REGISTRY_IMPL = "{testnet["attackRegistryImpl"]}"
TESTNET_MOCK_REGISTRY_MODERATOR = "{testnet["mockRegistryModerator"]}"

# -----------------------------------------------------------------------------
# CreateX-supported chains
# Source: https://github.com/pcaversaccio/createx#createx-deployments
# -----------------------------------------------------------------------------

{production}

{test}
'''


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "deployments_path",
        nargs="?",
        type=Path,
        default=DEFAULT_DEPLOYMENTS_PATH,
        help=f"Path to deployments.json (default: {DEFAULT_DEPLOYMENTS_PATH})",
    )
    args = parser.parse_args()

    deployments_path = args.deployments_path.expanduser().resolve()
    if not deployments_path.is_file():
        sys.exit(f"Not a file: {deployments_path}")

    data = json.loads(deployments_path.read_text())
    TARGET.write_text(render_module(data))

    print(f"Wrote {TARGET}")
    print(
        f"  mainnet={data['networks']['626']['chainId']}, "
        f"testnet={data['networks']['627']['chainId']}, "
        f"createx production={len(data['createx']['production'])}, "
        f"test={len(data['createx']['test'])}"
    )


if __name__ == "__main__":
    main()
