"""Regenerate battlechain/abi.py from cyfrin/battlechain-lib root ABI artifacts.

The canonical source of each ABI is the language-neutral JSON emitted by
`scripts/codegen.mjs` at the repository root:
    <battlechain-lib>/abis/<name>.json

These files are framework-agnostic raw ABI arrays (no forge dependency), the
same artifacts the JS package consumes. This script reads them and emits
`battlechain/abi.py` with stable constant names.

Usage:
    python tools/gen_abi.py                       # defaults to ../../abis
    python tools/gen_abi.py /path/to/abis
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

# Maps the root ABI artifact filename (without extension) to the Python
# constant name we emit. Order here is the order emitted in abi.py.
ARTIFACTS = {
    "agreementFactory": "AGREEMENT_FACTORY_ABI",
    "agreement": "AGREEMENT_ABI",
    "attackRegistry": "ATTACK_REGISTRY_ABI",
    "registry": "REGISTRY_ABI",
    "deployer": "DEPLOYER_ABI",
    "registryModerator": "MOCK_REGISTRY_MODERATOR_ABI",
}

# Package root is two levels up from this file (tools/ -> battlechain-lib-py/).
PACKAGE_ROOT = Path(__file__).resolve().parent.parent
# The abis/ directory lives at the battlechain-lib repo root, two levels above
# the package (battlechain-lib-py/ -> packages/ -> battlechain-lib/).
DEFAULT_ABIS_PATH = PACKAGE_ROOT.parent.parent / "abis"
TARGET = PACKAGE_ROOT / "battlechain" / "abi.py"


def load_abi(abis_dir: Path, name: str) -> list[dict]:
    """Read the raw ABI array from abis/<name>.json."""
    artifact = abis_dir / f"{name}.json"
    if not artifact.is_file():
        sys.exit(f"Missing ABI artifact: {artifact}\nDid scripts/codegen.mjs run?")
    data = json.loads(artifact.read_text())
    if not isinstance(data, list):
        sys.exit(f"Expected a JSON array of ABI items in {artifact}, got {type(data).__name__}")
    return data


def render_module(abis: dict[str, list[dict]]) -> str:
    header = '''"""ABI fragments for BattleChain protocol contracts.

Auto-generated by tools/gen_abi.py from cyfrin/battlechain-lib root ABI artifacts.
Do not edit manually — regenerate with:
    python tools/gen_abi.py [/path/to/abis]
"""

from typing import Any

# Each ABI is a list of function/event definitions in the standard JSON format
# accepted by boa.loads_abi(...) and web3.py.
'''
    chunks = [header]
    for name, py_name in ARTIFACTS.items():
        rendered = json.dumps(abis[name], indent=4)
        chunks.append(
            f"\n# Source: abis/{name}.json\n{py_name}: list[dict[str, Any]] = {rendered}\n"
        )
    chunks.append(
        "\n\n__all__ = [\n" + "".join(f'    "{name}",\n' for name in ARTIFACTS.values()) + "]\n"
    )
    return "".join(chunks)


def _ruff_format(path: Path) -> None:
    """Normalize the emitted file with `ruff format` so it is formatter-clean.

    The ABI bodies come from `json.dumps`, which differs from ruff's preferred
    layout (collapsed short dicts, trailing commas). Running ruff makes the
    generated output deterministic and pass `ruff format --check`.
    """
    result = subprocess.run(
        ["ruff", "format", str(path)],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        sys.exit(f"ruff format failed on {path} (exit {result.returncode}):\n{result.stderr}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "abis_path",
        nargs="?",
        type=Path,
        default=DEFAULT_ABIS_PATH,
        help=f"Path to the abis/ directory (default: {DEFAULT_ABIS_PATH})",
    )
    args = parser.parse_args()

    abis_dir = args.abis_path.expanduser().resolve()
    if not abis_dir.is_dir():
        sys.exit(f"Not a directory: {abis_dir}")

    abis = {name: load_abi(abis_dir, name) for name in ARTIFACTS}
    TARGET.write_text(render_module(abis))
    _ruff_format(TARGET)

    counts = ", ".join(f"{py}={len(abis[name])}" for name, py in ARTIFACTS.items())
    print(f"Wrote {TARGET}")
    print(f"  {counts}")


if __name__ == "__main__":
    main()
