/**
 * Regenerate src/abi.ts from the canonical battlechain-lib ABI artifacts.
 *
 * Source of truth: the ROOT-level abis/*.json produced by canonical codegen
 * (../../abis relative to this package). No forge dependency.
 *
 * Usage:
 *   npx tsx tools/gen-abi.ts                 # defaults to ../../abis
 *   npx tsx tools/gen-abi.ts /path/to/abis
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Maps the ABI artifact file (abis/<name>.json) to the TS constant name we emit.
const ARTIFACTS: Record<string, string> = {
  agreementFactory: "AGREEMENT_FACTORY_ABI",
  agreement: "AGREEMENT_ABI",
  attackRegistry: "ATTACK_REGISTRY_ABI",
  registry: "REGISTRY_ABI",
  deployer: "DEPLOYER_ABI",
};

const DEFAULT_ABIS_PATH = path.resolve(__dirname, "..", "..", "..", "abis");
const TARGET = path.resolve(__dirname, "..", "src", "abi.ts");

function loadAbi(abisRoot: string, name: string): unknown[] {
  const artifact = path.join(abisRoot, `${name}.json`);
  if (!fs.existsSync(artifact)) {
    throw new Error(`Missing ABI artifact: ${artifact}`);
  }
  const data = JSON.parse(fs.readFileSync(artifact, "utf8"));
  if (!Array.isArray(data)) {
    throw new Error(`ABI artifact is not an array: ${artifact}`);
  }
  return data;
}

function renderModule(abis: Record<string, unknown[]>): string {
  const header = `/**
 * ABI fragments for BattleChain protocol contracts.
 *
 * Auto-generated by tools/gen-abi.ts from the canonical battlechain-lib ABI
 * artifacts (../../abis/*.json). Do not edit manually — regenerate with
 * \`npm run gen-abi\`.
 */

/* eslint-disable */
`;
  const chunks = [header];
  for (const [file, name] of Object.entries(ARTIFACTS)) {
    const rendered = JSON.stringify(abis[file], null, 2);
    chunks.push(
      `\n// Source: abis/${file}.json\nexport const ${name} = ${rendered} as const;\n`,
    );
  }
  return chunks.join("");
}

function main(): void {
  const args = process.argv.slice(2);
  const abisPath = args[0] ? path.resolve(args[0]) : DEFAULT_ABIS_PATH;
  if (!fs.existsSync(abisPath)) {
    console.error(`Not a directory: ${abisPath}`);
    process.exit(1);
  }

  const abis: Record<string, unknown[]> = {};
  for (const file of Object.keys(ARTIFACTS)) {
    abis[file] = loadAbi(abisPath, file);
  }

  fs.writeFileSync(TARGET, renderModule(abis));
  const counts = Object.entries(ARTIFACTS)
    .map(([file, name]) => `${name}=${abis[file].length}`)
    .join(", ");
  console.log(`Wrote ${TARGET}`);
  console.log(`  ${counts}`);
}

main();
